# Generated by Django 2.1.1 on 2018-10-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20181011_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='song_title',
        ),
        migrations.AddField(
            model_name='description',
            name='song_text',
            field=models.CharField(default='hello', max_length=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='album',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=99999),
        ),
    ]
